
# 监控服务配置
spring:
  application:
    name: seven-core
  boot:
    admin:
      url: http://localhost:8081/core
# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /core

# profile配置
spring.profiles.active: dev

# 数据库配置
spring.datasource:
  url: ${mysql.url}
  username: ${mysql.username}
  password: ${mysql.password}
  initial-size: 5
  min-idle: 2
  max-active: 20
  test-on-borrow: true
  driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info

